name: CommandManager
version: 1.0
main: com.commandmanager.CommandManager
api-version: 1.12
description: A plugin to manage command permissions and custom messages
author: YourName
commands:
  commandmanager:
    description: Main command for CommandManager plugin
    usage: /<command> [reload|help]
    aliases: [cmdmgr, cm]
    permission: commandmanager.admin
    permission-message: &cYou don't have permission to use this command!
permissions:
  commandmanager.admin:
    description: Allows access to CommandManager admin commands
    default: op
    children:
      commandmanager.reload: true
  commandmanager.reload:
    description: Allows reloading of configuration
    default: op